# CodeRabbit config

reviews:
  ignore:
    - "node_modules/**"
    - "dist/**"
    - "*.lock"
    - "*.snap"

  rules:
    style: true         # Enable style checks
    formatting: true    # Enable formatting checks
    complexity: true
    security: true

  draft_prs: false

  max_comments: 8

  # Always leave a summary comment even if no issues are found
  always_comment: true
  summary_only_if_no_issues: true
